version: "3.7"

services:
  api_service:
    image: "spring-boot-dc3:v1"
    build: .
    restart: always
    ports:
      - 8088:8088
    networks:
      - zerocode_lk_network
    environment:
      SERVER_PORT: 8088
      TZ: Asia/Colombo

networks:
  zerocode_lk_network: